apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops-cats-dogs
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.9.0
          ports:
            - containerPort: 5000
              name: http
          command: ["mlflow", "server"]
          args:
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--backend-store-uri=sqlite:///mlflow/mlflow.db"
            - "--default-artifact-root=/mlflow/artifacts"
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: mlflow-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops-cats-dogs
  labels:
    app: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      name: http
